question_operation = [
    {"question": "Trata de adaptarse a la organización."},
    {"question": "Muestra lealtad y apego a aspectos críticos de la organización."},
    {"question": "Expresa orgullo por la empresa promoviendo los valores de la misma al interior y al exterior."},
    {"question": "Comprende situaciones y entiende aspectos básicos, analiza los problemas identificando las causas- efectos de los mismos."},
    {"question": "Utiliza herramientas de análisis para identificar las causas de los problemas (Excel, diagramas)"},
    {"question": "Identifica los temas clave para dar solución desde la causa raíz."},
    {"question": "Desarrolla relaciones de colaboración y confianza con personas de su equipo y de otras áreas buscando la colaboración."},
    {"question": "Desarrolla relaciones de largo plazo con su equipo de trabajo y si fuere el caso, con clientes, colaboradores externos y proveedores de confianza en beneficio de la empresa"},
    {"question": "Se relaciona con personal clave para el mejoramiento continuo (interno y externo) a partir de relaciones de confianza."},
    {"question": "Actúa con sentido de urgencia y no espera que el problema se resuelva solo."},
    {"question": "Define las acciones correctivas necesarias para evitar o atenuar los riesgos identificados que pudieran convertirse en problemas más graves."},
    {"question": "Se anticipa y toma acción para evitar problemas al desarrollar planes y estrategias para evitar crisis futuras."},
    {"question": "Utiliza múltiples medios para comunicarse, ajusta su lenguaje, estilo y estrategia de comunicación de acuerdo con las características y necesidades de las personas."},
    {"question": "Apela a la razón, con datos e información de interés para comunicarse eficientemente con otras personas."},
    {"question": "Identifica las reacciones de las otras personas y ajusta sus mensajes para influir positivamente."},
]